edition = "2024"

# max_width = 1000
# hard_tabs = false
# tab_spaces = 1
# use_small_heuristics = "Max"

# fn_call_width = 1000
# attr_fn_like_width = 1000
# struct_lit_width = 1000
# struct_variant_width = 1000
# array_width = 1000
# chain_width = 1000
# single_line_if_else_max_width = 1000


# imports_granularity = "Crate"
# reorder_imports = true
# remove_unused_imports = true

# fn_single_line = true
# where_single_line = true
# format_strings = false
# wrap_comments = false
# normalize_comments = false
# format_macro_matchers = true
# overflow_delimited_expr = true

